version: '3.8'

services:
  api:
    image: 810129/retell-api:latest
    # En Swarm se recomienda usar redes externas para comunicación entre stacks
    volumes:
      - ./credentials:/app/credentials
    environment:
      - REDIS_URL=redis://redis:6379/0
      - WHATSAPP_TOKEN=${WHATSAPP_TOKEN}
      - WHATSAPP_PHONE_ID=${WHATSAPP_PHONE_ID}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    networks:
      - public_net
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.retell-api.rule=Host(`demoinmobiliaria.serviglobal.co`)"
        - "traefik.http.routers.retell-api.entrypoints=websecure"
        - "traefik.http.routers.retell-api.tls.certresolver=myresolver"
        - "traefik.http.services.retell-api.loadbalancer.server.port=8000"

  redis:
    image: redis/redis-stack-server:latest
    volumes:
      - redis_data:/data
    networks:
      - public_net

networks:
  public_net:
    external: true

volumes:
  redis_data: